# Generated by Django 4.2.4 on 2023-09-27 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(max_length=6)),
                ('phoneNumber', models.BigIntegerField(max_length=10)),
                ('Qualification', models.CharField(max_length=20)),
                ('Address', models.TextField(max_length=120)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=100)),
                # ('image',models.ImageField(upload_to='images')),
            ],
        ),
    ]
