# Generated by Django 4.2.4 on 2023-09-28 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0002_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='c:/Users/ssadula/Pictures/p1.png', upload_to='images'),
        ),
    ]
