# Generated by Django 4.2.4 on 2023-09-28 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0003_user_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access', models.BooleanField(default=True)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.user')),
            ],
        ),
    ]
