# Generated by Django 4.2.4 on 2023-09-29 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0004_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='access',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userss', to='student_management_app.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='C:/Users/ssadula/Pictures/StudentManagamentProject/media/images/p1.png', upload_to='images'),
        ),
    ]
